button_changepwd = "//div[contains(text(),'Change Password') or contains(text(), 'Cambia password')]"
button_newpwd = "//input[@id='newPassword']"
button_cnfmpwd = "//input[@id='confirmPassword']"
button_changepassword = "//span[contains(text(),'Change Password') or contains(text(), 'Cambia password')]"
button_chngpwdconfrm = "//button[@id='message_dialog_close']"
text_popupaftercharvalidation = "//div[@id='message-dialog-content-id']"
button_cancel = "//button[@id='Cancel']"
