admin_menu_open="//div[@id='F102']"
um_menu_open="//div[@id='F10203']"
textbox_user_search="//input[@type='text']"
button_Add="//button[@id='0_Add']"
radiobutton_enabled="//input[@id='user-enable']"
textbox_username="//input[@id='userName']"
textbox_password="//input[@id='password']"
textbox_confirmpassword="//input[@id='confirmPassword']"
dropdown_salutation="//div[contains(@class, 'MuiSelect-root-2010')]"
dropdown_Mr_salutation="//li[@id='0_01']"
button_cancel_user="//span[contains(text(),'Cancel')]"
radiobutton_uselection="//tbody/tr/td/div/span/span/input"