admin_menu_open = "//div[@id='F102']"
um_menu_open = "//div[@id='F10203']"
textbox_user_search = "//input[@type='text']"
button_userimport = "//div[contains(text(),'Import Users') or contains(text(),'Importa utenti')]"
textbox_importfile = "//input[@id='file']"
button_import_dialogue = "//span[contains(text(),'Importare') or contains(text(),'Import')]"
message_validation= "//div[@id='message-dialog-content-id']"
Button_dialogue_ok = "//button[@id='message_dialog_close']"
Button_dialogue_cancel = "//button[@id='Cancel']"
Button_updategrid = "//button[@id='refresh_table_view_column_button']"